[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["mkdir -p streams", "ffmpeg -version"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
